version: '3'

services:
  apache:
    build: ./apache
    ports:
      - "80:80"
    networks:
      - lamp-network

  php:
    build: ./php
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    networks:
      - lamp-network

  mariadb:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: world_build
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

volumes:
  db_data:

networks:
  lamp-network:
    external: false

