version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "80:80"
    volumes:
      - ./apache/html:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    build: ./mariadb
    env_file:
    - text.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    build: ./phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
    env_file:
    - text.env
    depends_on:
      - mariadb

volumes:
  mariadb_data:

